// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Styles for the typeface used in captions.
enum TypefaceStyle {
  normal,
  bold,
  italic,
  boldItalic,
}

/// The type of edge effect for caption text.
enum EdgeType {
  /// Edge type is not specified.
  unspecified,
  /// No edge effect.
  none,
  /// Outline edge effect.
  outline,
  /// Drop shadow edge effect.
  dropShadow,
  /// Raised edge effect.
  raised,
  /// Depressed edge effect.
  depressed,
}

/// Represents typeface details including weight and family name.
class Typeface {
  Typeface({
    this.style,
    this.weight,
    this.isBold,
    this.isItalic,
    this.systemFontFamilyName,
  });

  /// The style of the typeface (normal, bold, etc.).
  TypefaceStyle? style;

  /// The numerical weight of the typeface (e.g., 400, 700).
  int? weight;

  /// Whether the typeface is bold.
  bool? isBold;

  /// Whether the typeface is italic.
  bool? isItalic;

  /// The name of the system font family.
  String? systemFontFamilyName;

  List<Object?> _toList() {
    return <Object?>[
      style,
      weight,
      isBold,
      isItalic,
      systemFontFamilyName,
    ];
  }

  Object encode() {
    return _toList();  }

  static Typeface decode(Object result) {
    result as List<Object?>;
    return Typeface(
      style: result[0] as TypefaceStyle?,
      weight: result[1] as int?,
      isBold: result[2] as bool?,
      isItalic: result[3] as bool?,
      systemFontFamilyName: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Typeface || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(style, other.style) && _deepEquals(weight, other.weight) && _deepEquals(isBold, other.isBold) && _deepEquals(isItalic, other.isItalic) && _deepEquals(systemFontFamilyName, other.systemFontFamilyName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NativeCaptionStyle {
  NativeCaptionStyle({
    this.foregroundColor,
    this.backgroundColor,
    this.edgeColor,
    this.edgeType,
    this.windowColor,
    this.typeface,
  });

  int? foregroundColor;

  int? backgroundColor;

  int? edgeColor;

  EdgeType? edgeType;

  int? windowColor;

  Typeface? typeface;

  List<Object?> _toList() {
    return <Object?>[
      foregroundColor,
      backgroundColor,
      edgeColor,
      edgeType,
      windowColor,
      typeface,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCaptionStyle decode(Object result) {
    result as List<Object?>;
    return NativeCaptionStyle(
      foregroundColor: result[0] as int?,
      backgroundColor: result[1] as int?,
      edgeColor: result[2] as int?,
      edgeType: result[3] as EdgeType?,
      windowColor: result[4] as int?,
      typeface: result[5] as Typeface?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCaptionStyle || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(foregroundColor, other.foregroundColor) && _deepEquals(backgroundColor, other.backgroundColor) && _deepEquals(edgeColor, other.edgeColor) && _deepEquals(edgeType, other.edgeType) && _deepEquals(windowColor, other.windowColor) && _deepEquals(typeface, other.typeface);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TypefaceStyle) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is EdgeType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is Typeface) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NativeCaptionStyle) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : TypefaceStyle.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : EdgeType.values[value];
      case 131:
        return Typeface.decode(readValue(buffer)!);
      case 132:
        return NativeCaptionStyle.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CaptionManagerApi {
  /// Constructor for [CaptionManagerApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CaptionManagerApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool?> isEnabled() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.caption_manager.CaptionManagerApi.isEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as bool?;
  }

  Future<bool?> isCallCaptioningEnabled() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.caption_manager.CaptionManagerApi.isCallCaptioningEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as bool?;
  }

  Future<bool?> isSystemAudioCaptioningEnabled() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.caption_manager.CaptionManagerApi.isSystemAudioCaptioningEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as bool?;
  }

  Future<bool?> isSystemAudioCaptioningUiEnabled() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.caption_manager.CaptionManagerApi.isSystemAudioCaptioningUiEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as bool?;
  }

  Future<double?> getFontScale() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.caption_manager.CaptionManagerApi.getFontScale$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as double?;
  }

  Future<String?> getLocale() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.caption_manager.CaptionManagerApi.getLocale$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  Future<NativeCaptionStyle?> getUserStyle() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.caption_manager.CaptionManagerApi.getUserStyle$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as NativeCaptionStyle?;
  }

  Future<void> openCaptionSetting() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.caption_manager.CaptionManagerApi.openCaptionSetting$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
