// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CaptionManagerApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Styles for the typeface used in captions. */
enum class TypefaceStyle(val raw: Int) {
  NORMAL(0),
  BOLD(1),
  ITALIC(2),
  BOLD_ITALIC(3);

  companion object {
    fun ofRaw(raw: Int): TypefaceStyle? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The type of edge effect for caption text. */
enum class EdgeType(val raw: Int) {
  /** Edge type is not specified. */
  UNSPECIFIED(0),
  /** No edge effect. */
  NONE(1),
  /** Outline edge effect. */
  OUTLINE(2),
  /** Drop shadow edge effect. */
  DROP_SHADOW(3),
  /** Raised edge effect. */
  RAISED(4),
  /** Depressed edge effect. */
  DEPRESSED(5);

  companion object {
    fun ofRaw(raw: Int): EdgeType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Represents typeface details including weight and family name.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Typeface (
  /** The style of the typeface (normal, bold, etc.). */
  val style: TypefaceStyle? = null,
  /** The numerical weight of the typeface (e.g., 400, 700). */
  val weight: Long? = null,
  /** Whether the typeface is bold. */
  val isBold: Boolean? = null,
  /** Whether the typeface is italic. */
  val isItalic: Boolean? = null,
  /** The name of the system font family. */
  val systemFontFamilyName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Typeface {
      val style = pigeonVar_list[0] as TypefaceStyle?
      val weight = pigeonVar_list[1] as Long?
      val isBold = pigeonVar_list[2] as Boolean?
      val isItalic = pigeonVar_list[3] as Boolean?
      val systemFontFamilyName = pigeonVar_list[4] as String?
      return Typeface(style, weight, isBold, isItalic, systemFontFamilyName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      style,
      weight,
      isBold,
      isItalic,
      systemFontFamilyName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Typeface
    return CaptionManagerApiPigeonUtils.deepEquals(this.style, other.style) && CaptionManagerApiPigeonUtils.deepEquals(this.weight, other.weight) && CaptionManagerApiPigeonUtils.deepEquals(this.isBold, other.isBold) && CaptionManagerApiPigeonUtils.deepEquals(this.isItalic, other.isItalic) && CaptionManagerApiPigeonUtils.deepEquals(this.systemFontFamilyName, other.systemFontFamilyName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CaptionManagerApiPigeonUtils.deepHash(this.style)
    result = 31 * result + CaptionManagerApiPigeonUtils.deepHash(this.weight)
    result = 31 * result + CaptionManagerApiPigeonUtils.deepHash(this.isBold)
    result = 31 * result + CaptionManagerApiPigeonUtils.deepHash(this.isItalic)
    result = 31 * result + CaptionManagerApiPigeonUtils.deepHash(this.systemFontFamilyName)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCaptionStyle (
  val foregroundColor: Long? = null,
  val backgroundColor: Long? = null,
  val edgeColor: Long? = null,
  val edgeType: EdgeType? = null,
  val windowColor: Long? = null,
  val typeface: Typeface? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCaptionStyle {
      val foregroundColor = pigeonVar_list[0] as Long?
      val backgroundColor = pigeonVar_list[1] as Long?
      val edgeColor = pigeonVar_list[2] as Long?
      val edgeType = pigeonVar_list[3] as EdgeType?
      val windowColor = pigeonVar_list[4] as Long?
      val typeface = pigeonVar_list[5] as Typeface?
      return NativeCaptionStyle(foregroundColor, backgroundColor, edgeColor, edgeType, windowColor, typeface)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      foregroundColor,
      backgroundColor,
      edgeColor,
      edgeType,
      windowColor,
      typeface,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCaptionStyle
    return CaptionManagerApiPigeonUtils.deepEquals(this.foregroundColor, other.foregroundColor) && CaptionManagerApiPigeonUtils.deepEquals(this.backgroundColor, other.backgroundColor) && CaptionManagerApiPigeonUtils.deepEquals(this.edgeColor, other.edgeColor) && CaptionManagerApiPigeonUtils.deepEquals(this.edgeType, other.edgeType) && CaptionManagerApiPigeonUtils.deepEquals(this.windowColor, other.windowColor) && CaptionManagerApiPigeonUtils.deepEquals(this.typeface, other.typeface)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CaptionManagerApiPigeonUtils.deepHash(this.foregroundColor)
    result = 31 * result + CaptionManagerApiPigeonUtils.deepHash(this.backgroundColor)
    result = 31 * result + CaptionManagerApiPigeonUtils.deepHash(this.edgeColor)
    result = 31 * result + CaptionManagerApiPigeonUtils.deepHash(this.edgeType)
    result = 31 * result + CaptionManagerApiPigeonUtils.deepHash(this.windowColor)
    result = 31 * result + CaptionManagerApiPigeonUtils.deepHash(this.typeface)
    return result
  }
}
private open class CaptionManagerApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TypefaceStyle.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EdgeType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Typeface.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCaptionStyle.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TypefaceStyle -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is EdgeType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is Typeface -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeCaptionStyle -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CaptionManagerApi {
  fun isEnabled(): Boolean?
  fun isCallCaptioningEnabled(): Boolean?
  fun isSystemAudioCaptioningEnabled(): Boolean?
  fun isSystemAudioCaptioningUiEnabled(): Boolean?
  fun getFontScale(): Double?
  fun getLocale(): String?
  fun getUserStyle(): NativeCaptionStyle?

  companion object {
    /** The codec used by CaptionManagerApi. */
    val codec: MessageCodec<Any?> by lazy {
      CaptionManagerApiPigeonCodec()
    }
    /** Sets up an instance of `CaptionManagerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CaptionManagerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caption_manager.CaptionManagerApi.isEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isEnabled())
            } catch (exception: Throwable) {
              CaptionManagerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caption_manager.CaptionManagerApi.isCallCaptioningEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isCallCaptioningEnabled())
            } catch (exception: Throwable) {
              CaptionManagerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caption_manager.CaptionManagerApi.isSystemAudioCaptioningEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isSystemAudioCaptioningEnabled())
            } catch (exception: Throwable) {
              CaptionManagerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caption_manager.CaptionManagerApi.isSystemAudioCaptioningUiEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isSystemAudioCaptioningUiEnabled())
            } catch (exception: Throwable) {
              CaptionManagerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caption_manager.CaptionManagerApi.getFontScale$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getFontScale())
            } catch (exception: Throwable) {
              CaptionManagerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caption_manager.CaptionManagerApi.getLocale$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getLocale())
            } catch (exception: Throwable) {
              CaptionManagerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.caption_manager.CaptionManagerApi.getUserStyle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getUserStyle())
            } catch (exception: Throwable) {
              CaptionManagerApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
